name: Publish Haddock documentation on GitHub Pages

on:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up build tools
        id: setup
        uses: haskell-actions/setup@v2
        with:
          ghc-version: 9.12
          cabal-version: 3.16

      - name: Configure
        shell: bash
        run: cabal configure --enable-documentation

      - name: Generate the plan
        shell: bash
        run: cabal build all --enable-documentation --dry-run

      - name: Restore cached dependencies
        uses: actions/cache/restore@v4
        id: cache
        env:
          key: deploy-docs-to-github-pages-${{ runner.os }}-${{ steps.setup.outputs.cabal-version }}-${{ steps.setup.outputs.ghc-version }}-${{ github.job }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ env.key }}-${{ hashFiles('**/plan.json') }}
          restore-keys: ${{ env.key }}

      - name: Build docs
        shell: bash
        run: cabal haddock-project --hackage

      - name: Save dependencies cache
        uses: actions/cache/save@v4
        if: ${{ steps.cache.outputs.cache-primary-key != steps.cache.outputs.cache-matched-key }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Enrich documentation footers
        shell: bash
        run: |
          COMMIT_HASH="${{ github.sha }}"
          REPO_URL="https://github.com/${{ github.repository }}/tree/${COMMIT_HASH}"
          
          # Ensure haddocks directory exists
          if [ ! -d "haddocks" ]; then
            echo "ERROR: haddocks directory not found. Documentation build may have failed."
            exit 1
          fi
          
          # Ensure there are HTML files to process
          if [ "$(find haddocks -name "*.html" -type f | wc -l)" -eq 0 ]; then
            echo "ERROR: No HTML files found in haddocks directory. Documentation generation may have failed."
            exit 1
          fi

          # Find all HTML files and replace the footer (using Linux sed syntax)
          find haddocks -name "*.html" -type f -exec sed -i \
            "s|<div id=\"footer\"><p>Produced by <a href=\"http://www.haskell.org/haddock/\">Haddock</a> version 2.30.0</p></div>|<div id=\"footer\"><p>Produced from commit <a href=\"${REPO_URL}\">${COMMIT_HASH:0:7}</a> by <a href=\"http://www.haskell.org/haddock/\">Haddock</a> version 2.30.0</p></div>|g" {} \;

      - name: Add .nojekyll (avoid Jekyll processing)
        run: touch haddocks/.nojekyll

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: haddocks

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
