name: Format the code

on:
  workflow_call:

jobs:

  format:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: nikita-volkov/cabal-fmt.github-action@v1.1.0
      - uses: nikita-volkov/ormolu.github-action@v3.0.0
      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Format
