name: Release the lib to Hackage

on:
  workflow_call:
    secrets:
      hackage-token:
        required: true
    inputs:
      prefix-tag-with-v:
        type: boolean
        default: true
        required: false
      master-branch:
        type: string
        default: master
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:

  format:
    uses: ./.github/workflows/format-stage.yaml
    secrets: inherit
  
  test:
    uses: ./.github/workflows/test-stage.yaml
    secrets: inherit
  
  release:
    needs:
      - format
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Release
        uses: nikita-volkov/release-haskell-package.github-action@v1.2.0
        with:
          hackage-token: ${{ secrets.hackage-token }}
          version-bump-place: ${{ fromJSON('{"supermajor":0,"major":1,"minor":2,"patch":3}')[github.ref_name] }}
          main-branch: ${{ inputs.master-branch }}
          prefix-tag-with-v: ${{ inputs.prefix-tag-with-v }}
