name: Release the lib to Hackage

on:
  workflow_call:
    secrets:
      HACKAGE_TOKEN:
        required: true
    inputs:
      prefix-tag-with-v:
        type: boolean
        default: true
        required: false
      master-branch:
        type: string
        default: master
        required: false
      docs:
        type: boolean
        default: false
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: Hackage
      # TODO: Determine the release URL on Hackage and put here:
      # url: ...
    steps:
      - uses: actions/checkout@v4

      - name: Release
        uses: nikita-volkov/release-haskell-package.github-action@v1
        with:
          hackage-token: ${{ secrets.HACKAGE_TOKEN }}
          version-bump-place: ${{ fromJSON('{"supermajor":0,"major":1,"minor":2,"patch":3}')[github.ref_name] }}
          main-branch: ${{ inputs.master-branch }}
          prefix-tag-with-v: ${{ inputs.prefix-tag-with-v }}
          docs: ${{ inputs.docs }}
