name: Release the lib to Hackage

on:
  push:
    branches:
      - supermajor
      - major
      - minor
      - patch

concurrency:
  group: release
  cancel-in-progress: false

jobs:

  format:
    uses: ./.github/workflows/format-stage.yaml
    secrets: inherit
  
  test:
    uses: ./.github/workflows/test-stage.yaml
    secrets: inherit
  
  release:
    needs:
      - format
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Release
        uses: nikita-volkov/release-haskell-package.github-action@v1.2.0
        with:
          hackage-token: ${{ secrets.HACKAGE_TOKEN }}
          version-bump-place: ${{ fromJSON('{"supermajor":0,"major":1,"minor":2,"patch":3}')[github.ref_name] }}
          main-branch: master
          prefix-tag-with-v: true
