name: Compile, test and check the docs

on:
  push:
    branches:
      - master
  pull_request:
  workflow_call:

jobs:

  test:

    strategy:
      fail-fast: false
      matrix:
        include:
          - ghc: '8.8.1'
          - ghc: latest
            ghc-options: -Werror -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wredundant-constraints -Wunused-packages -Wno-name-shadowing -Wno-unused-matches -Wno-unused-do-bind -Wno-type-defaults

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.8

      - name: Generate cabal.project.freeze
        run: cabal freeze --enable-tests --enable-benchmarks

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - name: Install deps and compile
        run: cabal build --enable-tests -j +RTS -A128m -n2m -N -RTS --ghc-options="${{ matrix.ghc-options }}"

      - name: Test
        run: cabal test --test-show-details always

      - name: Run Haddock
        run: cabal haddock
