name: Compile, test and check the docs

on:
  workflow_call:
    inputs:
      minimal-ghc:
        type: string
        default: 8.8.1
        required: false

jobs:

  test:

    strategy:
      fail-fast: false
      matrix:
        include:
          - ghc: ${{ inputs.minimal-ghc }}
          - ghc: latest
            ghc-options: -Werror -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wredundant-constraints -Wunused-packages -Wno-name-shadowing -Wno-unused-matches -Wno-unused-do-bind -Wno-type-defaults

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up GHC ${{ matrix.ghc }}
        id: setup
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Check cabal file
        run: cabal check

      - name: Configure the build
        run: |
          cabal configure --enable-tests --enable-benchmarks --enable-documentation
          cabal build --dry-run

      - name: Restore cached dependencies
        uses: actions/cache/restore@v3
        id: cache
        env:
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ env.key }}-plan-${{ hashFiles('**/plan.json') }}
          restore-keys: ${{ env.key }}-
          
      - name: Install dependencies
        run: cabal build all --only-dependencies --enable-tests --enable-benchmarks --enable-documentation -j +RTS -A128m -n2m -N -RTS --ghc-options="${{ matrix.ghc-options }}"

      - name: Save dependencies cache
        uses: actions/cache/save@v3
        if: ${{ steps.cache.outputs.cache-primary-key != steps.cache.outputs.cache-matched-key }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Build
        run: cabal build all --enable-tests --enable-benchmarks -j +RTS -A128m -n2m -N -RTS --ghc-options="${{ matrix.ghc-options }}"

      - name: Test
        run: cabal test all --test-show-details streaming -j +RTS -A128m -n2m -N -RTS --ghc-options="${{ matrix.ghc-options }}"

      - name: Build docs
        run: cabal haddock -j +RTS -A128m -n2m -N -RTS --ghc-options="${{ matrix.ghc-options }}"
